chore: add rules to .gitignore
linuxdeepin/dtkdevice pull request #56
Opened 2023-07-03 09:39 UTC by length-of-time

对.gitignore进行修改，防止doxygen-theme对项目污染

Log: 增加了文件忽视规则,防止doxygen-theme对项目污染

Issue: https://github.com/linuxdeepin/dtk/issues/99

2023-07-03 09:50 UTC, xzl01 commented on .gitignore
> +docs/doxygen-theme/
结尾需要空行

2023-07-04 02:12 UTC, kegechen requested changes
amend

2023-07-04 03:32 UTC, kegechen approved these changes

2023-07-04 03:35 UTC, length-of-time commented
/merge

2023-07-04 03:35 UTC, merged